import java.util.ArrayList;
/*
 * DO NOT EDIT THIS FILE
 */
public interface IMeeting { 
    /*
     * calculate and return the day which have
     * biggest/largest number of meetings
     */
    public String f1(ArrayList<Meeting> a);        
   
    /*
     * calculate and return the number of meetings which are 
     * on a specific day, given day as input parameter
     */
    public int f2(ArrayList<Meeting> a, String day);
}
